[template]
prefix = "/counter"
src = "nginx.tmpl"
dest = "/etc/nginx/nginx.conf"
owner = "nginx"
mode = "0644"
keys = [ 
  "/subdomain",
  "/domain",
]
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "/usr/sbin/service nginx reload"
