kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-nfs-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/efs/coreos/db-nfs-pv"
